import type { Product } from '@/types/Product';

export const productsData: Product[] = [
  {
    id: 1,
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    oldPrice: 3500000,
    isNew: false,
    image: 'images/products/syltherine.jpg',
  },
  {
    id: 2,
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 250000,
    oldPrice: null,
    isNew: false,
    image: '/images/products/leviosa.jpg',
  },
  {
    id: 3,
    name: 'Lolito',
    description: 'Luxuaray big sofa',
    price: 7000000,
    oldPrice: 14000000,
    isNew: false,
    image: '/images/products/lolito.jpg',
  },
  {
    id: 4,
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    oldPrice: null,
    isNew: true,
    image: '/images/products/respira.jpg',
  },
  {
    id: 5,
    name: 'Grifo',
    description: 'Night lamp',
    price: 1500000,
    oldPrice: null,
    isNew: false,
    image: '/images/products/grifo.jpg',
  },
  {
    id: 6,
    name: 'Muggo',
    description: 'Small mug',
    price: 150000,
    oldPrice: null,
    isNew: true,
    image: '/images/products/muggo.jpg',
  },
  {
    id: 7,
    name: 'Pingky',
    description: 'Cute bed set',
    price: 7000000,
    oldPrice: 14000000,
    isNew: false,
    image: '/images/products/pingky.jpg',
  },
  {
    id: 8,
    name: 'Potty',
    description: 'Minimalist flower pot',
    price: 500000,
    oldPrice: null,
    isNew: true,
    image: '/images/products/potty.jpg',
  },
];
